import { Anek_Bangla } from "next/font/google";
import "./globals.css";

const anekBangla = Anek_Bangla({ subsets: ["latin"] });

export const metadata = {
  title: "Framer Motion R&D",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={anekBangla.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
