import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const anekBangla = Anek_Bangla({ subsets: ["latin"] });

export const metadata = {
  title: "Framer Motion R&D",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={anekBangla.className}>
        <Navbar />

        <div className="h-[calc(100vh - 6rem)]">{children}</div>
      </body>
    </html>
  );
}
